     , sum(base.num_pitches)                                     as num_pitches
     , sum(num_zone)                                             as num_zone
     , sum(total_velo)                                           as total_velo
     , sum(num_velo)                                             as num_velo
     , sum(num_armside)                                          as num_armside
     , sum(num_gloveside)                                        as num_gloveside
     , sum(num_inside)                                           as num_inside
     , sum(num_outside)                                          as num_outside
     , sum(num_horizontal_middle)                                as num_horizontal_middle
     , sum(num_high)                                             as num_high
     , sum(num_middle)                                           as num_middle
     , sum(num_low)                                              as num_low
     , sum(num_heart)                                            as num_heart
     , sum(num_early)                                            as num_early
     , sum(num_late)                                             as num_late
     , sum(num_behind)                                           as num_behind
     , sum(num_non_bip_strike)                                   as num_non_bip_strike
     , sum(num_batted_ball_event)                                as num_batted_ball_event
     , sum(num_early_bip)                                        as num_early_bip
     , sum(num_fastball)                                         as num_fastball
     , sum(num_secondary)                                        as num_secondary
     , sum(num_early_secondary)                                  as num_early_secondary
     , sum(num_late_secondary)                                   as num_late_secondary
     , sum(num_called_strike)                                    as num_called_strike
     , sum(num_early_called_strike)                              as num_early_called_strike
     , sum(num_called_strike_plus_whiff)                         as num_called_strike_plus_whiff
     , sum(num_put_away)                                         as num_put_away
     , sum(num_swing)                                            as num_swing
     , sum(num_whiff)                                            as num_whiff
     , sum(num_contact)                                          as num_contact
     , sum(num_foul)                                             as num_foul
     , sum(num_first_pitch_swing)                                as num_first_pitch_swing
     , sum(num_first_pitch_strike)                               as num_first_pitch_strike
     , sum(num_true_first_pitch_strike)                          as num_true_first_pitch_strike
     , sum(num_plus_pitch)                                       as num_plus_pitch
     , sum(num_z_swing)                                          as num_z_swing
     , sum(num_z_contact)                                        as num_z_contact
     , sum(num_o_swing)                                          as num_o_swing
     , sum(num_o_contact)                                        as num_o_contact
     , sum(num_early_o_swing)                                    as num_early_o_swing
     , sum(num_early_o_contact)                                  as num_early_o_contact
     , sum(num_late_o_swing)                                     as num_late_o_swing
     , sum(num_late_o_contact)                                   as num_late_o_contact
     , sum(num_pulled_bip)                                       as num_pulled_bip
     , sum(num_opposite_bip)                                     as num_opposite_bip
     , sum(num_line_drive)                                       as num_line_drive
     , sum(num_fly_ball)                                         as num_fly_ball
     , sum(num_if_fly_ball)                                      as num_if_fly_ball
     , sum(num_ground_ball)                                      as num_ground_ball
     , sum(num_weak_bip)                                         as num_weak_bip
     , sum(num_medium_bip)                                       as num_medium_bip
     , sum(num_hard_bip)                                         as num_hard_bip
     , sum(num_outs)                                             as num_outs
     , sum(num_pa)                                               as num_pa
     , sum(num_ab)                                               as num_ab
     , sum(num_1b)                                               as num_1b
     , sum(num_2b)                                               as num_2b
     , sum(num_3b)                                               as num_3b
     , sum(num_hr)                                               as num_hr
     , sum(num_bb)                                               as num_bb
     , sum(num_ibb)                                              as num_ibb
     , sum(num_hbp)                                              as num_hbp
     , sum(num_sacrifice)                                        as num_sacrifice
     , sum(num_k)                                                as num_k
     , sum(num_hit)                                              as num_hit
     , sum(num_runs)                                             as num_runs
     , sum(num_barrel)                                           as num_barrel
     , sum(total_launch_speed)                                   as total_launch_speed
     , sum(num_launch_speed)                                     as num_launch_speed
     , sum(total_launch_angle)                                   as total_launch_angle
     , sum(num_launch_angle)                                     as num_launch_angle
     , sum(total_release_extension)                              as total_release_extension
     , sum(num_release_extension)                                as num_release_extension
     , sum(total_spin_rate)                                      as total_spin_rate
     , sum(num_spin_rate)                                        as num_spin_rate
     , sum(total_x_movement)                                     as total_x_movement
     , sum(num_x_movement)                                       as num_x_movement
     , sum(total_z_movement)                                     as total_z_movement
     , sum(num_z_movement)                                       as num_z_movement
--from pl_leaderboard_v2_daily base
