FROM debian:buster-slim

ARG TIMEZONE

ENV TZ=${TIMEZONE}
ENV DEBIAN_FRONTEND='noninteractive'

RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone

# Add debian backports
RUN echo "deb http://deb.debian.org/debian/ buster-backports main" > /etc/apt/sources.list.d/buster-backports.list

ARG POSTGRES_VERSION
ARG POSTGRES_PORT
ARG CLICKHOUSE_PORT

# Install packges
RUN apt-get update && \
    apt-get install -y --no-install-recommends \
        software-properties-common \
        apt-transport-https \
        ca-certificates \
        debconf-utils \
        curl \
        iptables \
        iproute2 \
        net-tools \
        procps \
        openresolv \
        dnsutils \
        vim \
        kafkacat \
        jq \
        wget \
        inotify-tools \
        bc \
        curl \
        gnupg \
        build-essential \
        lsb-release \
        git \
        cmake \
        libpoco-dev \
        libssl-dev \
        libicu-dev \
        unixodbc-dev \
        openssl \
        unixodbc \
        gcc \
        libc-dev \
        g++ \
        python3 \
        python3-pip \
        dnsutils \
        zip \
        unzip && \
    curl https://www.postgresql.org/media/keys/ACCC4CF8.asc | gpg --dearmor | tee /etc/apt/trusted.gpg.d/apt.postgresql.org.gpg >/dev/null && \
    echo "deb http://apt.postgresql.org/pub/repos/apt $(lsb_release -cs)-pgdg main" > /etc/apt/sources.list.d/pgdg.list && \
    apt-get update && \
    apt-get install -y --no-install-recommends \
        postgresql-client-${POSTGRES_VERSION} && \
    apt-get clean

# Add main work dir to PATH
WORKDIR /fieldsets
ENV PATH="/fieldsets:${PATH}"

# Postgresql interserver port
EXPOSE ${POSTGRES_PORT}

# Clickhouse interserver port
EXPOSE 9000
EXPOSE 9009
EXPOSE ${CLICKHOUSE_PORT}

ENTRYPOINT ["/entrypoint-fieldsets.sh"]