FROM debian:buster-slim

ARG TIMEZONE

ENV TZ=${TIMEZONE}
ENV DEBIAN_FRONTEND='noninteractive'

ARG POSTGRES_VERSION
ARG POSTGRES_PORT
ARG CLICKHOUSE_PORT
ARG GRAPHQL_PORT
ARG MONGO_PORT
ARG MONGO_VERSION

# Install packges
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone && \
    echo "deb http://deb.debian.org/debian/ buster-backports main" > /etc/apt/sources.list.d/buster-backports.list && \
    apt-get update && \
    apt-get install -y --no-install-recommends \
        software-properties-common \
        apt-transport-https \
        ca-certificates \
        debconf-utils \
        curl \
        iptables \
        iproute2 \
        net-tools \
        procps \
        openresolv \
        dnsutils \
        vim \
        kafkacat \
        jq \
        wget \
        inotify-tools \
        bc \
        curl \
        gnupg \
        build-essential \
        lsb-release \
        git \
        cmake \
        libpoco-dev \
        libssl-dev \
        libicu-dev \
        unixodbc-dev \
        openssl \
        unixodbc \
        gcc \
        libc-dev \
        g++ \
        python3 \
        python3-pip \
        dnsutils \
        zip \
        unzip && \
    curl https://www.postgresql.org/media/keys/ACCC4CF8.asc | gpg --dearmor | tee /etc/apt/trusted.gpg.d/apt.postgresql.org.gpg >/dev/null && \
    echo "deb http://apt.postgresql.org/pub/repos/apt $(lsb_release -cs)-pgdg main" > /etc/apt/sources.list.d/pgdg.list && \
    wget -qO - https://www.mongodb.org/static/pgp/server-${MONGO_VERSION}.0.asc | apt-key add - && \
    echo "deb [ arch=amd64,arm64 ] https://repo.mongodb.org/apt/ubuntu bionic/mongodb-org/${MONGO_VERSION}.0 multiverse" | tee /etc/apt/sources.list.d/mongodb-org-${MONGO_VERSION}.0.list && \
    apt-get update && \
    apt-get install -y --no-install-recommends \
        postgresql-client-${POSTGRES_VERSION} \ 
        mongocli \
        mongodb-mongosh && \
    wget -O /tmp/mongodb-tools.deb https://fastdl.mongodb.org/tools/db/mongodb-database-tools-debian92-x86_64-100.5.2.deb && \
    dpkg -i /tmp/mongodb-tools.deb && \
    rm -f /tmp/mongodb-tools.deb && \
    cd /tmp && \
    curl -sL https://deb.nodesource.com/setup_17.x -o nodesource_setup.sh && \
    chmod +x ./nodesource_setup.sh && ./nodesource_setup.sh && \
    apt-get update && \
    apt-get install -y --no-install-recommends \
        nodejs && \
    apt-get clean

# Add main work dir to PATH
WORKDIR /fieldsets
ENV PATH="/fieldsets:${PATH}"

# Postgresql interserver port
EXPOSE ${POSTGRES_PORT}

# Clickhouse interserver port
EXPOSE 9000
EXPOSE 9009
EXPOSE ${CLICKHOUSE_PORT}

# Mongo port
EXPOSE ${MONGO_PORT}

# Graphql Port
EXPOSE ${GRAPHQL_PORT}

ENTRYPOINT ["/entrypoint-fieldsets.sh"]
