services:
    fieldsets-local:
        image: ${CONTAINER_REGISTRY:-fieldsets}/fieldsets-local:${FIELDSETS_LOCAL_VERSION:-latest}
        build:
            context: ./
            dockerfile: ${FIELDSETS_LOCAL_CONFIG_PATH:-./}Dockerfile
            args:
                TIMEZONE: ${TIMEZONE:-America/New_York}
                POSTGRES_VERSION: ${POSTGRES_VERSION:-15}
                BUILD_CONTEXT_PATH: ${FIELDSETS_LOCAL_CONFIG_PATH:-./}
                SSH_PORT: ${SSH_PORT:-1022}
                DOTNET_VERSION: "8.0"
        container_name: fieldsets-local
        hostname: fieldsets-local
        tty: ${ENABLE_TERMINAL:-true}
        environment:
            DOTNET_VERSION: "8.0"
            ENVIRONMENT: ${ENVIRONMENT:-dev-local}
            FIELDSETS_INFRASTRUCTURE_ROLE: ${FIELDSETS_INFRASTRUCTURE_ROLE:-node}
            SSH_KEY_PATH: ${SSH_KEY_PATH:-~/.ssh/}
            SSH_PORT: ${SSH_PORT:-1022}
            FIELDSETS_SESSION_KEY: ${FIELDSETS_SESSION_KEY:-fieldsets_rsa}
            PLUGINS_PATH: "/usr/local/fieldsets/plugins/"
            LIB_PATH: "/usr/local/fieldsets/lib/"
            APPS_PATH: "/usr/local/fieldsets/apps/"
            DATA_PATH: "/usr/local/fieldsets/data/"
            FIELDSETS_LOCAL_HOST: ${FIELDSETS_LOCAL_HOST:-172.28.0.6}
            FIELDSETS_LOCAL_VERSION: ${FIELDSETS_LOCAL_VERSION:-latest}
            PUID: ${LOCAL_UID:-1000}
            PGID: ${LOCAL_GID:-1000}
            CHECKPOINT_PATH: ${CHECKPOINT_PATH:-/checkpoints/}
            ENABLE_DEBUG_MODE: ${ENABLE_DEBUG_MODE:-true}
            ENABLE_LOGGING: ${ENABLE_LOGGING:-false} # Write logs to DB
            FIELDSETS_DB: ${FIELDSETS_DB:-postgres}
            FIELDSETS_DB_HOST: ${FIELDSETS_DB_HOST:-${POSTGRES_HOST:-172.28.0.7}}
            FIELDSETS_DB_PORT: ${FIELDSETS_DB_PORT:-${POSTGRES_PORT:-5423}}
            FIELDSETS_DB_VERSION: ${FIELDSETS_DB_VERSION:-${POSTGRES_VERSION:-15}}
            FIELDSETS_DB_USER: ${FIELDSETS_DB_USER:-${POSTGRES_USER:-postgres}}
            FIELDSETS_DB_PASSWORD: ${FIELDSETS_DB_PASSWORD:-${POSTGRES_PASSWORD:-fieldsets}}
            FIELDSETS_DB_NAME: ${FIELDSETS_DB_NAME:-${POSTGRES_DB:-fieldsets}}
            FIELDSETS_DB_SCHEMA: ${FIELDSETS_DB_SCHEMA:-${POSTGRES_SCHEMA:-fieldsets}}
            FIELDSETS_DB_READER_ROLE: ${FIELDSETS_DB_READER_ROLE:-${POSTGRES_READER_ROLE:-fieldsets_reader_role}}
            FIELDSETS_DB_READER_ROLE_PASSWORD: ${FIELDSETS_DB_READER_ROLE_PASSWORD:-${POSTGRES_READER_ROLE_PASSWORD:-${POSTGRES_PASSWORD:-fieldsets}}}
            FIELDSETS_DB_WRITER_ROLE: ${FIELDSETS_DB_WRITER_ROLE:-${POSTGRES_WRITER_ROLE:-fieldsets_writer_role}}
            FIELDSETS_DB_WRITER_ROLE_PASSWORD: ${FIELDSETS_DB_WRITER_ROLE_PASSWORD:-${POSTGRES_WRITER_ROLE_PASSWORD:-${POSTGRES_PASSWORD:-fieldsets}}}
            FIELDSETS_DB_TRIGGER_ROLE: ${FIELDSETS_DB_TRIGGER_ROLE:-${POSTGRES_TRIGGER_ROLE:-fieldsets_trigger_role}}
            FIELDSETS_DB_TRIGGER_ROLE_PASSWORD: ${FIELDSETS_DB_TRIGGER_ROLE_PASSWORD:-${POSTGRES_TRIGGER_ROLE_PASSWORD:-${POSTGRES_PASSWORD:-fieldsets}}}
            FIELDSETS_STORE: ${FIELDSETS_STORE:-clickhouse}
            FIELDSETS_STORE_HOST: ${FIELDSETS_STORE_HOST:-${CLICKHOUSE_HOST:-172.28.0.5}}
            FIELDSETS_STORE_PORT: ${FIELDSETS_STORE_PORT:-${CLICKHOUSE_PORT:-8123}}
            FIELDSETS_STORE_VERSION: ${FIELDSETS_STORE_VERSION:-${CLICKHOUSE_VERSION:-24}}
            FIELDSETS_STORE_USER: ${FIELDSETS_STORE_USER:-${CLICKHOUSE_USER:-default}}
            FIELDSETS_STORE_PASSWORD: ${FIELDSETS_STORE_PASSWORD:-${CLICKHOUSE_PASSWORD:-fieldsets}}
            FIELDSETS_STORE_NAME: ${FIELDSETS_STORE_NAME:-${CLICKHOUSE_DB:-fieldsets}}
            FIELDSETS_STORE_SCHEMA: ${FIELDSETS_STORE_SCHEMA:-${CLICKHOUSE_SCHEMA:-fieldsets}}
            FIELDSETS_CACHE: ${FIELDSETS_CACHE:-memcached}
            FIELDSETS_CACHE_NAME: ${FIELDSETS_CACHE_NAME:-"fieldsets-cache"}
            FIELDSETS_CACHE_HOST: ${FIELDSETS_CACHE_HOST:-${FIELDSETS_LOCAL_HOST:-:-172.28.0.6}}
            FIELDSETS_CACHE_PORT: ${FIELDSETS_CACHE_PORT:-11211}
            FIELDSETS_LOGGER: ${FIELDSETS_LOGGER:-fluentbit}}
            FIELDSETS_LOGGER_HOST: ${FIELDSETS_LOGGER_HOST:-172.28.0.2}}
            FIELDSETS_LOGGER_PORT: ${FIELDSETS_LOGGER_PORT:-24224}}
        volumes:
            - ${FIELDSETS_LOCAL_CONFIG_PATH:-./}apt-preferences:/etc/preferences
            - ${FIELDSETS_LOCAL_CONFIG_PATH:-./}.bashrc:/root/.bashrc
            - ${FIELDSETS_LOCAL_CONFIG_PATH:-./}.bash_profile:/root/.profile
            - ${FIELDSETS_LOCAL_CONFIG_PATH:-./}init/:/docker-entrypoint-init.d/
            - ${SSH_KEY_PATH:-~/.ssh/}:/root/.ssh/
            - ${FIELDSETS_LOCAL_CONFIG_PATH:-./}sql/:/usr/local/fieldsets/sql/
            - ${FIELDSETS_LOCAL_CONFIG_PATH:-./}entrypoint.sh:/docker-entrypoint.sh
            - ${FIELDSETS_LOCAL_CONFIG_PATH:-./}bin:/usr/local/fieldsets/bin/
            - ${FIELDSETS_LOCAL_CONFIG_PATH:-./}lib:/usr/local/fieldsets/lib/
            - ${FIELDSETS_LOCAL_CONFIG_PATH:-./}plugins:/usr/local/fieldsets/plugins/
            - ${FIELDSETS_LOCAL_CONFIG_PATH:-./}data:/usr/local/fieldsets/data/
            - ${FIELDSETS_LOCAL_CONFIG_PATH:-./}src:/usr/local/fieldsets/apps/
            - local-data:/data

volumes:
    local-data:
        driver: local
        name: fieldsets-local-data
