services:
    fieldsets-local:
        image: ${CONTAINER_REGISTRY:-fieldsets}/fieldsets-local:${FIELDSETS_LOCAL_VERSION:-latest}
        build:
            context: ./
            dockerfile: ${FIELDSETS_LOCAL_CONFIG_PATH:-./}Dockerfile
            args:
                TIMEZONE: ${TIMEZONE:-America/New_York}
                POSTGRES_VERSION: ${POSTGRES_VERSION:-15}
                BUILD_CONTEXT_PATH: ${FIELDSETS_LOCAL_CONFIG_PATH:-./}
                SSH_PORT: ${SSH_PORT:-1022}
                DOTNET_VERSION: "8.0"
        container_name: fieldsets-local
        hostname: fieldsets-local
        tty: ${ENABLE_TERMINAL:-true}
        environment:
            DOTNET_VERSION: "8.0"
            ENVIRONMENT: ${ENVIRONMENT:-dev-local}
            FIELDSETS_INFRASTRUCTURE_ROLE: ${FIELDSETS_INFRASTRUCTURE_ROLE:-node}
            FIELDSETS_DB: ${FIELDSETS_DB:-postgres}
            SSH_KEY_PATH: ${SSH_KEY_PATH:-~/.ssh/}
            SSH_PORT: ${SSH_PORT:-1022}
            FIELDSETS_SESSION_HOST: ${FIELDSETS_SESSION_HOST}
            FIELDSETS_SESSION_KEY: ${FIELDSETS_SESSION_KEY:-fieldsets_rsa}
            FIELDSETS_STORE: ${FIELDSETS_STORE:-clickhouse}
            LOGGER_HOST: ${LOGGER_HOST:-172.28.0.2}
            LOGGER_PORT: ${LOGGER_PORT:-24224}
            PLUGINS_PATH: "/usr/local/fieldsets/plugins/"
            LIB_PATH: "/usr/local/fieldsets/lib/"
            APPS_PATH: "/usr/local/fieldsets/apps/"
            DATA_PATH: "/usr/local/fieldsets/data/"
            FIELDSETS_LOCAL_VERSION: ${FIELDSETS_LOCAL_VERSION:-latest}
            PUID: ${LOCAL_UID:-1000}
            PGID: ${LOCAL_GID:-1000}
            CLICKHOUSE_HOST: ${CLICKHOUSE_HOST:-172.28.0.5}
            CLICKHOUSE_PORT: ${CLICKHOUSE_PORT:-8123}
            CLICKHOUSE_DB: ${CLICKHOUSE_DB:-fieldsets}
            CLICKHOUSE_USER: ${CLICKHOUSE_USER:-default}
            CLICKHOUSE_PASSWORD: ${CLICKHOUSE_PASSWORD:-fieldsets}
            POSTGRES_VERSION: ${POSTGRES_VERSION:-15}
            POSTGRES_USER: ${POSTGRES_USER:-postgres}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-fieldsets}
            POSTGRES_HOST: ${POSTGRES_HOST:-172.28.0.7}
            POSTGRES_DB: ${POSTGRES_DB:-fieldsets}
            POSTGRES_PORT: ${POSTGRES_PORT:-5432}
            POSTGRES_READER_ROLE: ${POSTGRES_READER_ROLE:-fieldsets_reader_role}
            POSTGRES_READER_ROLE_PASSWORD: ${POSTGRES_READER_ROLE_PASSWORD:-}
            POSTGRES_WRITER_ROLE: ${POSTGRES_WRITER_ROLE:-fieldsets_writer_role}
            POSTGRES_WRITER_ROLE_PASSWORD: ${POSTGRES_WRITER_ROLE_PASSWORD:-}
            POSTGRES_TRIGGER_ROLE: ${POSTGRES_TRIGGER_ROLE:-fieldsets_trigger_role}
            POSTGRES_TRIGGER_ROLE_PASSWORD: ${POSTGRES_TRIGGER_ROLE_PASSWORD:-}
            FIELDSETS_LOCAL_HOST: ${FIELDSETS_LOCAL_HOST:-172.28.0.6}
            CHECKPOINT_PATH: ${CHECKPOINT_PATH:-/checkpoints/}
            ENABLE_DEBUG_MODE: ${ENABLE_DEBUG_MODE:-true}
            ENABLE_LOGGING: ${ENABLE_LOGGING:-false} # Write logs to DB
        volumes:
            - ${FIELDSETS_LOCAL_CONFIG_PATH:-./}apt-preferences:/etc/preferences
            - ${FIELDSETS_LOCAL_CONFIG_PATH:-./}.bashrc:/root/.bashrc
            - ${FIELDSETS_LOCAL_CONFIG_PATH:-./}.bash_profile:/root/.profile
            - ${FIELDSETS_LOCAL_CONFIG_PATH:-./}init/:/docker-entrypoint-init.d/
            - ${SSH_KEY_PATH:-~/.ssh/}:/root/.ssh/
            - ${FIELDSETS_LOCAL_CONFIG_PATH:-./}sql/:/usr/local/fieldsets/sql/
            - ${FIELDSETS_LOCAL_CONFIG_PATH:-./}entrypoint.sh:/docker-entrypoint.sh
            - ${FIELDSETS_LOCAL_CONFIG_PATH:-./}bin:/usr/local/fieldsets/bin/
            - ${FIELDSETS_LOCAL_CONFIG_PATH:-./}lib:/usr/local/fieldsets/lib/
            - ${FIELDSETS_LOCAL_CONFIG_PATH:-./}plugins:/usr/local/fieldsets/plugins/
            - ${FIELDSETS_LOCAL_CONFIG_PATH:-./}data:/usr/local/fieldsets/data/
            - ${FIELDSETS_LOCAL_CONFIG_PATH:-./}src:/usr/local/fieldsets/apps/
            - local-data:/data

volumes:
    local-data:
        driver: local
        name: fieldsets-local-data
