ARG CLICKHOUSE_VERSION
FROM yandex/clickhouse-server:${CLICKHOUSE_VERSION:-22}

ENV DEBIAN_FRONTEND='noninteractive'
ARG POSTGRES_VERSION
ARG POSTGRES_PORT

# Install necessary packges
RUN apt-get update && \
    apt-get install -y --no-install-recommends \
        curl \
        ca-certificates \
        gnupg \
        build-essential \
        lsb-release \
        git \
        cmake \
        libpoco-dev \
        libssl-dev \
        libicu-dev \
        unixodbc-dev \
        jq \
        openssl \
        libicu66 \
        unixodbc \
        gcc \
        libc-dev \
        g++ \
        python3 \
        python3-pip \
        dnsutils \
        zip \
        unzip && \
    curl https://www.postgresql.org/media/keys/ACCC4CF8.asc | gpg --dearmor | tee /etc/apt/trusted.gpg.d/apt.postgresql.org.gpg >/dev/null && \
    sh -c "echo 'deb http://apt.postgresql.org/pub/repos/apt $(lsb_release -cs)-pgdg main' > /etc/apt/sources.list.d/pgdg.list" && \
    apt-get update && \
    apt-get install -y --no-install-recommends \
        postgresql-client-${POSTGRES_VERSION} && \
    apt-get clean

# Postgresql interserver port
EXPOSE ${POSTGRES_PORT}

# Clickhouse interserver port
EXPOSE 9000
EXPOSE 9009

# Clickhouse ODBC & JDBC Port
EXPOSE 9018
EXPOSE 9019

######
# ODBC Table engine is not compiled here as it takes time, but you may find uncommenting below useful for your project if you need to connect to another DBMS
######

#RUN git clone --recursive https://github.com/ClickHouse/clickhouse-odbc.git && \
#    cd clickhouse-odbc && \
#    mkdir build && \
#    cd build && \
#    cmake -DCMAKE_BUILD_TYPE=RelWithDebInfo .. && \
#    cmake --build . --config RelWithDebInfo && \
#    cp driver/*.so /usr/local/lib/ && \
#    chown clickhouse:clickhouse /usr/local/lib/libclickhouse*.so

#COPY ./config/clickhouse/odbcinst.ini /root/odbcinst.ini
#COPY ./config/clickhouse/odbc.ini /root/odbc.ini

#RUN odbcinst -i -d -f /root/odbcinst.ini && \
#    odbcinst -i -s -l -f /root/odbc.ini



