# Insert the content of this file into ~/.odbc.ini or /etc/odbc.ini files.

[ODBC Data Sources]
ClickHouse DSN (ANSI)    = ClickHouse ODBC Driver (ANSI)
ClickHouse DSN (Unicode) = ClickHouse ODBC Driver (Unicode)

[staging-clickhouse]
DRIVER = ClickHouse ODBC Driver (Unicode)
USERNAME = default
DATABASE = default
SERVER = 
PORT = 30901
PROTO = http
TIMEOUT = 200
