ARG POSTGRES_VERSION
FROM postgres:${POSTGRES_VERSION}

ENV DEBIAN_FRONTEND='noninteractive'
ARG POSTGRES_VERSION
ARG CLICKHOUSE_PORT

# Install wireguard packges
RUN apt-get update && \
    apt-get install -y --no-install-recommends \
        postgresql-server-dev-${POSTGRES_VERSION} \
        postgresql-client-${POSTGRES_VERSION} \
        curl  \
        libcurl4 \
        libcurl4-openssl-dev \
        uuid-dev \
        build-essential \
        gnupg \
        apt-transport-https \
        lsb-release \
        wget \
        cmake \
        pkg-config \
        git \
        python3 \
        python3-pip \
        postgresql-${POSTGRES_VERSION}-python3-multicorn \
        python3-pycurl \
        zlib1g \
        zlib1g-dev \
        libevent-pthreads-* \
        libssl-dev \
        libzstd-dev \
        librdkafka-dev && \
    apt-get clean && \
    cd /tmp/ && \
    git clone https://github.com/adjust/clickhouse_fdw.git && \
    cd clickhouse_fdw && \
    mkdir build && cd build && \
    cmake .. && \
    make && make install && \
    cd /tmp/ && \
    git clone https://github.com/adjust/kafka_fdw && \
    cd kafka_fdw && \
    make && make install && \
    cd /tmp/ && \
    git clone https://github.com/EnterpriseDB/mongo_fdw.git && \
    cd mongo_fdw && \
    bash ./autogen.sh --with-master


# Clickhouse ports
EXPOSE 9000
EXPOSE 9009
EXPOSE ${CLICKHOUSE_PORT}

